### ISSUE TITLE
Make your PA/Project repos private (Academic Integrity violation)

### ISSUE THREAD

**Issue by niemasd** [Shushruth007/MyProjects#1]
By posting your PA/Project code publicly, you are explicitly violating the Academic Integrity policy of CSE 100. You need to make all of your PA/Project repos private, otherwise I will have to report this to the Academic Integrity Office.

**Comment by Shushruth007** [comment]
Done. Sorry for the trouble

**Comment by niemasd** [comment]
I see that you're addressing it now; thank you. Note, however, that simply deleting files from the GitHub Repo doesn't remove them: by design, version control keeps records even of deleted files. For example, I can still access the code from your older commits:

https://github.com/Shushruth007/MyProjects/commit/a137a89de417a3aced95593e698f5de60fb02ac9

You will need to completely undo those commits (or create a new repo):

https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git
